# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-28 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, unique=True, verbose_name='Club Name')),
                ('League', models.CharField(max_length=200, verbose_name='Club Name')),
                ('City', models.CharField(max_length=200, verbose_name='City')),
            ],
            options={
                'verbose_name_plural': 'Clubs',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='State')),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='State',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='Club.State'),
        ),
    ]
