# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-28 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='League',
            field=models.CharField(max_length=200, verbose_name='League Name'),
        ),
    ]
