# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-28 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0003_auto_20200428_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='State',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='Club.State'),
        ),
    ]
